// Generated by scripts/generate-known-agents.ts — do not edit by hand

export const WORKSPACE_KNOWN_AGENTS = [
  {
    id: "antigravity",
    configPath: ".gemini/antigravity",
    workspaceMarker: ".agent",
    paths: [
      { path: ".agent/", scope: "workspace", type: "directory", purpose: "marker" },
      { path: ".gemini/antigravity", scope: "home", type: "directory", purpose: "config" },
    ],
  },
  {
    id: "cursor",
    configPath: ".cursor",
    workspaceMarker: ".cursor",
    paths: [
      { path: ".cursor/", scope: "workspace", type: "directory", purpose: "marker" },
      { path: ".cursor", scope: "home", type: "directory", purpose: "config" },
    ],
  }
];
